"""Initial schema: users, user_profiles, career_passes, generated_cvs

Revision ID: 5d94399568e5
Revises: 
Create Date: 2025-11-09 17:19:57.924286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d94399568e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('career_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=False),
    sa.Column('pass_type', sa.Enum('PASS_30_DAYS', 'PASS_90_DAYS', name='passtype'), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_id')
    )
    op.create_index(op.f('ix_career_passes_user_id'), 'career_passes', ['user_id'], unique=False)
    op.create_table('generated_cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cv_name', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('job_offer_context', sa.Text(), nullable=True),
    sa.Column('cv_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gcs_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_cvs_created_at'), 'generated_cvs', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_cvs_user_id'), 'generated_cvs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_generated_cvs_user_id'), table_name='generated_cvs')
    op.drop_index(op.f('ix_generated_cvs_created_at'), table_name='generated_cvs')
    op.drop_table('generated_cvs')
    op.drop_index(op.f('ix_career_passes_user_id'), table_name='career_passes')
    op.drop_table('career_passes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
